version: "3.8"
name: rinha-spring
services:
  api1: &api
    image: hstreb/rinha-spring:0.0.1
    profiles: ["jvm"]
    depends_on:
      db:
        condition: service_healthy
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.75GB'
    healthcheck:
      test: curl -f localhost:8080/contagem-pessoas
      interval: 2s
      timeout: 1s
      retries: 30
  api2:
    <<: *api
    environment:
      - SERVER_PORT=8081
    healthcheck:
      test: curl -f localhost:8081/contagem-pessoas
      interval: 2s
      timeout: 1s
      retries: 30

  api-native1: &api-native
    image: hstreb/rinha-spring:0.0.1-native
    profiles: ["native"]
    depends_on:
      db:
        condition: service_healthy
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.75GB'
  api-native2:
    <<: *api-native
    environment:
      - SERVER_PORT=8081

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    profiles: ["jvm"]
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  nginx-native:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    profiles: ["native"]
    depends_on:
      - api-native1
      - api-native2
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'
  db:
    image: postgres:15.4-alpine
    hostname: db
    network_mode: "host"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha123
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.0GB'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha" ]
      interval: 2s
      timeout: 1s
      retries: 30
