version: "3.8"
services:
  api1:
    image: docker/rinha-spring:0.0.1
    hostname: api1
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
  api2:
    image: docker/rinha-spring:0.0.1
    hostname: api2
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'
  db:
    image: postgres:15.4-alpine
    hostname: db
    command: -p 5432
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha123
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.5GB'
